apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: my-app-2-cl-role
  namespace: hibiki-ito-pipeline-from-scratch
rules:
  - apiGroups:
      - triggers.tekton.dev
    resources:
      - triggerbindings
      - clusterinterceptors
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-app-2-cl-rolebinding
  namespace: hibiki-ito-pipeline-from-scratch
subjects:
  - kind: ServiceAccount
    name: build-bot
    namespace: hibiki-ito-pipeline-from-scratch
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: my-app-2-cl-role
